Feature/tdd
sabetech/tdd-ruby pull request #1
Opened 2022-09-01 12:55 UTC by teckim

### In this pull request:

- Added basic `linters` setup.
- Added TDD tests.

2022-09-01 16:11 UTC, sja-thedude requested changes
## Invalid Code Review Request ❌

Hi @teckim & @sabetech, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have a professional readme file. Kindly make sure you submit with a readme.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-02 07:35 UTC, danmainah requested changes
Hi @teckim  and @sabetech, 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ All linters are passing
✔️ Professional Readme
✔️ Correct gitflow

 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 07:35 UTC, danmainah commented on spec/solver_spec.rb
> +    it 'factorial should return 0 when input is 1' do
- [ ] Kindly check your factorial function , the test is failing:
![image](https://user-images.githubusercontent.com/61408860/188083644-2fec4820-92b3-4f7e-9a87-e7d499f6833e.png)

2022-09-02 08:40 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @sabetech, and @teckim👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://user-images.githubusercontent.com/83803414/188100174-62ae226e-2341-4b2a-ae80-28677970116e.png)

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 09:01 UTC, merged